services:
  - type: web
    name: block-resume
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_TECTONIC
        value: "0"
      - key: USE_TEXLIVE
        value: "1"
